### ISSUE TITLE
Fake Issue for comitting images

### ISSUE THREAD

**Issue by SSKale1** [ine-labs/AzureGoat#1]
IDOR
![1](https://user-images.githubusercontent.com/65826354/183736614-788630c2-4a4e-4f11-b1fc-6429a0b807e4.png)
![2](https://user-images.githubusercontent.com/65826354/183736625-3c1f0f69-4d0a-4da9-885a-be7168ee7dfa.png)
![3](https://user-images.githubusercontent.com/65826354/183736630-56788231-0810-45e7-a0de-3f22e75d7bac.png)
![4](https://user-images.githubusercontent.com/65826354/183736635-7c33ec2d-094e-4b72-9155-3186108b5021.png)
![5](https://user-images.githubusercontent.com/65826354/183736639-ce32b4f1-c2be-4009-bc0e-3899b0eaa34c.png)
![6](https://user-images.githubusercontent.com/65826354/183736649-bcaded1b-d533-4b4c-ab3f-4746ba8f14a6.png)

![7](https://user-images.githubusercontent.com/65826354/183736711-5cc1b6ed-7352-4218-98fe-be86d1553283.png)
![8](https://user-images.githubusercontent.com/65826354/183736722-131c2c79-8772-4a92-ac0e-72aa4e089bf1.png)
![9](https://user-images.githubusercontent.com/65826354/183736734-019b58e9-b192-41be-b2cc-71a2ff202d24.png)
![10](https://user-images.githubusercontent.com/65826354/183736753-3dabb27a-9529-4ec4-b1f2-41a7956b119e.png)
![11](https://user-images.githubusercontent.com/65826354/183736766-ae9c1b31-629d-4473-826f-e3b1b2bed8cf.png)
![12](https://user-images.githubusercontent.com/65826354/183736778-f6d0b617-5c50-4da5-a118-ac366481e46a.png)
![13](https://user-images.githubusercontent.com/65826354/183736791-7d2040ff-f350-47e4-9bda-d3c88fec8d15.png)
![14](https://user-images.githubusercontent.com/65826354/183736802-2b3c90b3-bd4e-4fd0-9b74-c3bd314cd613.png)
![15](https://user-images.githubusercontent.com/65826354/183736811-2fab83ea-eed7-42a9-9c1a-734d72b095a8.png)
![16](https://user-images.githubusercontent.com/65826354/183736817-92148556-9b01-40fd-8861-3c93d5ab7f44.png)
![17](https://user-images.githubusercontent.com/65826354/183736828-8f59e9a3-5569-4962-9ea9-8e4db9388b06.png)
![18](https://user-images.githubusercontent.com/65826354/183736838-17b40b0c-d32f-4731-be83-19e88e3824e7.png)

SSRF AZGOAT
![1](https://user-images.githubusercontent.com/65826354/183736905-97acb94c-6d4f-43ee-b39b-afea123dfc13.png)
![2](https://user-images.githubusercontent.com/65826354/183736908-b99181cf-1a18-4c4d-8aa0-94745acc353e.png)
![3](https://user-images.githubusercontent.com/65826354/183736922-58d59a85-89c7-4e14-9921-06276101466c.png)
![4](https://user-images.githubusercontent.com/65826354/183736928-4228e040-4d22-4004-81c4-50b6c1b4dd9b.png)
![5](https://user-images.githubusercontent.com/65826354/183736934-079d9148-2181-492f-bad0-0007ca8a794d.png)
![6](https://user-images.githubusercontent.com/65826354/183736943-a9739de9-4367-4762-bd08-4a17be6591c7.png)
![7](https://user-images.githubusercontent.com/65826354/183736953-4c3ef73f-56c2-49a3-8ed8-210aba0d14b8.png)
![8](https://user-images.githubusercontent.com/65826354/183736959-54984f43-ec62-4735-aa34-df78ff42459a.png)
![9](https://user-images.githubusercontent.com/65826354/183736970-75aa3899-7caa-4e66-a435-c68c818356d8.png)
![10](https://user-images.githubusercontent.com/65826354/183736980-abd1b03d-a100-440b-835b-b54bb41f79aa.png)
![11](https://user-images.githubusercontent.com/65826354/183736988-e44f051c-3738-4333-a1fe-4bbc63ce17cf.png)
![12](https://user-images.githubusercontent.com/65826354/183736998-4b64976d-dc81-4c26-95c4-348ef5bd64e2.png)

Security Misconfiguration

![1](https://user-images.githubusercontent.com/65826354/183737053-17881055-f5d4-42b0-9a16-12142264aeef.png)
![2](https://user-images.githubusercontent.com/65826354/183737061-b3b278e2-4d8d-44b5-92a8-573fb7e8233e.png)
![3](https://user-images.githubusercontent.com/65826354/183737069-2e77fe5a-fbfa-441f-a941-36f75761f36b.png)
![4](https://user-images.githubusercontent.com/65826354/183737091-922a2304-8dbd-4a6e-978a-fa129e97bbae.png)
![5](https://user-images.githubusercontent.com/65826354/183737106-b79d88fd-d5a2-4f21-86a6-70383dbe3143.png)
![6](https://user-images.githubusercontent.com/65826354/183737123-04b6feaf-99df-41a9-ba54-e950c306ce4e.png)
![7](https://user-images.githubusercontent.com/65826354/183737130-6d5a4df2-354c-4091-ada7-f37e9db75910.png)
![8](https://user-images.githubusercontent.com/65826354/183737138-cd8b817b-5d31-48af-a2ba-ffb7a2e31d00.png)
![9](https://user-images.githubusercontent.com/65826354/183737145-184f7906-4945-4e0c-bb72-b68c115211a9.png)
![10](https://user-images.githubusercontent.com/65826354/183737152-9f10b663-fdd5-477e-9ee1-083b40addfb7.png)
![11](https://user-images.githubusercontent.com/65826354/183737161-12180bbc-8737-4ecf-a650-94958e5b6265.png)
![12](https://user-images.githubusercontent.com/65826354/183737176-f0f26b23-70df-4a8f-9569-c134184aa457.png)
![13](https://user-images.githubusercontent.com/65826354/183737185-a28c4fbf-f484-4cf5-a103-c674b673d30f.png)
![14](https://user-images.githubusercontent.com/65826354/183737195-aca59c38-f63c-467a-8859-8e2d30c8a4ee.png)

Az Id Misconfig

![1](https://user-images.githubusercontent.com/65826354/183737316-807e8ff3-cfe8-4cc3-a4db-9e260dea3eb1.png)
![2](https://user-images.githubusercontent.com/65826354/183737322-916d1d8e-b8f6-4e6e-8e84-e3fcd7758acf.png)
![3](https://user-images.githubusercontent.com/65826354/183737331-91b0f964-b607-424f-a930-ebc7248eb52f.png)
![4](https://user-images.githubusercontent.com/65826354/183737337-f2f85115-8e8b-4c45-9002-a5768546b3e1.png)
![5](https://user-images.githubusercontent.com/65826354/183737343-4a4a5a29-ebc2-43c6-a001-cf34510e20dc.png)
![6](https://user-images.githubusercontent.com/65826354/183737348-4d2b9549-9359-4efd-a167-f112013488d9.png)
![7](https://user-images.githubusercontent.com/65826354/183737354-27fdcc60-58ec-45c8-a0c3-b0abf6d459a3.png)
![8](https://user-images.githubusercontent.com/65826354/183737359-b9ce3b71-1531-48a8-8ee7-6fc1cc689e91.png)
![10](https://user-images.githubusercontent.com/65826354/183737366-32394666-7473-4d38-a266-817cf66c0a68.png)
![11](https://user-images.githubusercontent.com/65826354/183737373-0d4de08c-4782-41e5-947d-7dee0ecf35e1.png)
![12](https://user-images.githubusercontent.com/65826354/183737383-9e752c90-fc05-444c-96ef-3f849973c62e.png)
![13](https://user-images.githubusercontent.com/65826354/183737393-71783bc1-0d89-4df4-94fc-dfccd7b444c2.png)
![14](https://user-images.githubusercontent.com/65826354/183737404-198f7ef3-8b93-4e59-b0dd-05624d7c50c4.png)
![15](https://user-images.githubusercontent.com/65826354/183737413-b1df1449-dd20-4ec3-9104-d7d487301fed.png)

ssrf for cosmosdb & storageaccount
![1](https://user-images.githubusercontent.com/65826354/183737518-9636cd66-8f8b-4b02-8895-fb2ef6a28ba9.png)
![2](https://user-images.githubusercontent.com/65826354/183737523-e807de5e-05ac-4699-a277-22de8088c4b5.png)
![3](https://user-images.githubusercontent.com/65826354/183737533-7db7a3fa-8d6b-4c59-9237-10c1bc1322b5.png)
![4](https://user-images.githubusercontent.com/65826354/183737538-de9cad78-853f-47ce-b085-e79718c5e98a.png)
![5](https://user-images.githubusercontent.com/65826354/183737548-8e227a83-1180-43cf-92d0-b1a18d2382c0.png)
![6](https://user-images.githubusercontent.com/65826354/183737555-61b21043-d83d-438d-943f-fec0bb50b4e0.png)
![7](https://user-images.githubusercontent.com/65826354/183737565-e22fef4e-4e05-4451-b09c-8b48b14bb365.png)
![8](https://user-images.githubusercontent.com/65826354/183737572-13c80a32-48f8-4237-bfc2-f52e441dda52.png)
![9](https://user-images.githubusercontent.com/65826354/183737585-9897592d-7f2c-4305-b0e3-90106f5a7c8d.png)
![10](https://user-images.githubusercontent.com/65826354/183737592-914855aa-4e42-4b6b-8b45-8af70c1f219c.png)
![11](https://user-images.githubusercontent.com/65826354/183737600-a5c3f93e-6304-4286-b1a7-93b6fb32e1c2.png)
![12](https://user-images.githubusercontent.com/65826354/183737610-84831db5-5e1d-4eeb-aa3f-3346b45371f3.png)
![13](https://user-images.githubusercontent.com/65826354/183737620-b9092b44-fcad-4d4b-b5a5-08307fa6f648.png)
![14](https://user-images.githubusercontent.com/65826354/183737643-5e66caaf-7d99-4a7e-9591-6cd5cadb9af6.png)
![16](https://user-images.githubusercontent.com/65826354/183737654-f8550a24-513d-4742-8f4a-35bc3e56fdf9.png)
![17](https://user-images.githubusercontent.com/65826354/183737669-dc444bb8-1a78-45cf-aa39-217f2c271709.png)
![18](https://user-images.githubusercontent.com/65826354/183737675-6ba5dabc-3765-4bcc-8835-fc176e5eaebe.png)
![19](https://user-images.githubusercontent.com/65826354/183737683-d867a786-5378-4e74-a3bc-9957b5b2e225.png)
![20](https://user-images.githubusercontent.com/65826354/183737690-2cc78369-448f-4e5a-a3f7-3b5f768319de.png)
![21](https://user-images.githubusercontent.com/65826354/183737701-85179921-b21f-4c90-a93d-4453bafe10ba.png)
![22](https://user-images.githubusercontent.com/65826354/183737710-b280e475-24fe-4b40-97e5-1ba1da2553af.png)
![23](https://user-images.githubusercontent.com/65826354/183737719-e5d0db41-c4cd-4a3f-854c-55c8f6265e33.png)
![24](https://user-images.githubusercontent.com/65826354/183737724-5165a1e2-3edd-4669-bb07-295345e496e0.png)
![25](https://user-images.githubusercontent.com/65826354/183737732-30460217-a4d6-477c-9d1c-c7f53781505e.png)
![26](https://user-images.githubusercontent.com/65826354/183737737-3d963462-6a67-4d10-b344-82922410b9d2.png)
![27](https://user-images.githubusercontent.com/65826354/183737746-91caec63-e3b8-4b0c-972b-b0d81c7caa06.png)
![28](https://user-images.githubusercontent.com/65826354/183737753-a716f0f2-e80c-43dd-8280-0e95c641b22b.png)
![29](https://user-images.githubusercontent.com/65826354/183737764-0828cabd-3575-439f-80eb-ac95f77daa99.png)
![30](https://user-images.githubusercontent.com/65826354/183737776-59eacefb-307a-4a7f-95f7-9b7463253568.png)
![31](https://user-images.githubusercontent.com/65826354/183737783-9f3003ca-e7f1-4d35-a200-f024bb3489b0.png)
![32](https://user-images.githubusercontent.com/65826354/183737793-fc277da3-ecee-4fa2-b153-938575cf43e8.png)
![33](https://user-images.githubusercontent.com/65826354/183737801-1f2a1467-f6e6-4cfa-8bda-ccd1668042a9.png)
![34](https://user-images.githubusercontent.com/65826354/183737811-30390897-fbc3-44b2-97a5-4ffd258df8ac.png)
![35](https://user-images.githubusercontent.com/65826354/183737821-8b27eb65-fab9-4ca5-af8f-5f1d245df848.png)

Readme

![1](https://user-images.githubusercontent.com/25884689/183741003-04609eaa-63fd-43c3-9851-d1e10b5763a9.png)
![2](https://user-images.githubusercontent.com/65826354/183737940-b1fa7b71-82cb-4744-af6a-22386c22a934.png)
![3](https://user-images.githubusercontent.com/65826354/183737954-2ede9a5b-0797-4eef-8329-9871c14327fd.png)
![4](https://user-images.githubusercontent.com/65826354/183737967-a2af9d1e-9805-4658-8055-f3f7ee982b63.png)
![5](https://user-images.githubusercontent.com/65826354/183737979-20c60ca1-14e0-4da9-a3c7-161ef9a62591.png)
![6](https://user-images.githubusercontent.com/25884689/183740988-9fa75f39-8c85-4db7-a5a9-c0f4acdb2783.png)
![logo](https://user-images.githubusercontent.com/25884689/183740998-da6f7ae7-2df0-4557-a6f5-2f0040ebe0dc.png)

**Comment by sherinsteph** [comment]
![202](https://user-images.githubusercontent.com/42687376/223097139-e22d6c72-4d19-490d-ab77-e8cb77cc37f0.png)
![303](https://user-images.githubusercontent.com/42687376/223097148-6b15b0a5-94de-4622-b607-ffccc238e919.png)
![404](https://user-images.githubusercontent.com/42687376/223097150-5886c2d7-5b7c-48c8-a30c-f5529ec8eb49.png)
![505](https://user-images.githubusercontent.com/42687376/223097152-a30a38cd-7d86-429b-9581-15118bb8c799.png)
![606](https://user-images.githubusercontent.com/42687376/223097155-427c4d2e-eeb3-434f-bd3e-66920c4e2ae3.png)
![707](https://user-images.githubusercontent.com/42687376/223097159-55fe76c7-bfcb-457f-9cb7-a56514e96681.png)
![808](https://user-images.githubusercontent.com/42687376/223097162-b837d122-b0fc-4607-bf59-e2bb36652c51.png)
![909](https://user-images.githubusercontent.com/42687376/223097167-3559a180-3a9e-4257-a592-ef4a6f7563da.png)
![1001](https://user-images.githubusercontent.com/42687376/223097171-4e5a4842-f720-4ab9-be57-7ac8febacd08.png)

**Comment by prnjl117** [comment]
![script](https://github.com/user-attachments/assets/b1168f4a-79c2-441e-8415-d9a67e547e8d)
