### ISSUE TITLE
local-exec provisioner error

### ISSUE THREAD

**Issue by hacknorris** [ine-labs/AzureGoat#3]
Hello! hoping to get some help or insight to this error when deploying the TF scripts.  I ran pip3 install --pre azure-cosmos which updated.  but still getting this local-exec provisioner error.  Am I missing another dependency?  
![image](https://user-images.githubusercontent.com/20147808/186207014-ad73f63d-b7d8-4e83-9b00-0dd736289f84.png)

**Comment by jeswinMathai** [comment]
Hello!

Can you please provide us with the OS details on which the deployment failed? It will help us in debugging the issue. 

The easiest way to deploy AzureGoat is via Cloudshell. I will request you to take a look at the following video: 

https://www.youtube.com/watch?v=_FIrMr8hDHY&list=PLcIpBb4raSZGdYHKpqIu5Boc2ziga4oGY&index=6

**Comment by hacknorris** [comment]
Thankyou Jeswin!  I was running from a Windows 11 Pro - Surface Book (azure cli version 2.25, terraform version 1.2.6).  But -- anyway -- deployed it through Cloudshell as you mentioned and it deployed beautifully smooth. thankyou!
