### ISSUE TITLE
Minor Typo in Role Assignment Code (Module 1 - part 5)

### ISSUE THREAD

**Issue by hacknorris** [ine-labs/AzureGoat#4]
Hello! just a quick note - found a minor typo in the role assignment copy code block for Module 1 - part 5.  "New-AzRoleAssignmnet"

![image](https://user-images.githubusercontent.com/20147808/190251483-e7e79af2-273d-4681-a7e5-219e6baac86e.png)

**Comment by SSKale1** [comment]
Thank you for bringing this to out notice.
